FROM node:18

# CREAMOS LA CARPETA DENTRO DEL CONTENEDOR DONDE SE TRABAJARÁ
WORKDIR /usr/src/app

# COPIAMOS EL PROYECTO A LA CARPETA
COPY . .

# INSTALAMOS LAS DEPENDENCIAS
RUN npm install
RUN npm i

# CONSTRUIMOS EL PROYECTO
RUN npm run build